セッション2
daikiumehara/Yumemi-ios-training pull request #2
Opened 2022-05-06 06:54 UTC by daikiumehara

課題のURL：https://github.com/yumemi-inc/ios-training/blob/main/Documentation/API.md

# 変更点
・Reloadを押したときにAPIで取得した天気が表示される

## 晴れ
![simulator_screenshot_7C3ED769-506E-4A42-AEF0-AEDE16823A06](https://user-images.githubusercontent.com/62703773/167081600-6e2df517-ce91-4938-aa1a-80c3817aebbc.png)

## 曇り
![simulator_screenshot_9083CF30-B093-46C3-AE2D-B8DADAF55262](https://user-images.githubusercontent.com/62703773/167081699-6446f430-2a75-46d6-9fe0-a6c8a0ca20ea.png)

## 雨
![simulator_screenshot_4D498D9E-D46E-4C11-B0DD-D3A2FDCBC036](https://user-images.githubusercontent.com/62703773/167081716-d27b4dab-0bf7-4328-a6a5-85abd5dffc01.png)

2022-05-06 09:09 UTC, ykws requested changes
きちんと責務を分割しており、コードが大変読みやすいです。
マージ先を session/1 にしてもらうと session/2 としての対応差分が明確になるのでレビューしやすいです。

気になる箇所についてコメントしているので確認をお願いします。

2022-05-06 09:09 UTC, ykws commented on Yumemi-ios-training/Client/WeatherClient.swift
> +        return Weather(rawValue: weather)!
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

ここはどういう意図で force unwrapping していますか？

2022-05-06 09:09 UTC, ykws commented on Yumemi-ios-training/Converter/WeatherConverter.swift
> +            return WeatherData(image: UIImage(named: "sunny")!, color: .red)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

`#imageLiteral(` を利用して画像を参照すると、静的なリソースと紐付けできるので安心です。

2022-05-06 09:37 UTC, daikiumehara commented on Yumemi-ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +{
そのような設定があるのは知りませんでした！
修正しました！

2022-05-06 09:42 UTC, daikiumehara commented on Yumemi-ios-training/Model/WeatherData.swift
> +import UIKit
そのように修正します！

2022-05-06 09:54 UTC, daikiumehara commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +protocol MainPresenterProtocol {
今まであまり理解してませんでしたが、そのような意味があったんですね！
修正しました！

2022-05-06 09:55 UTC, daikiumehara commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +class MainPresenter: NSObject, MainPresenterProtocol {
修正しました！

2022-05-06 10:21 UTC, daikiumehara commented on Yumemi-ios-training/Client/WeatherClient.swift
> +        return Weather(rawValue: weather)!
`sunny`,`cloudy`,`rainy`以外の値が返ってこないので、force unwrappingにしています。
後々直す必要が出てきそうなので、あまり良くないコードだと思っています。

2022-05-09 05:01 UTC, ykws commented on Yumemi-ios-training/Converter/WeatherConverter.swift
> +            return WeatherData(image: UIImage(named: "sunny")!, color: .red)
申し訳ありません！ `resourceName:` を端折ってしまいました。その記載であっています。

2022-05-09 08:28 UTC, novr commented on Yumemi-ios-training/Enums/Weather.swift
> +    static func create(_ weatherString: String) -> Weather {
[imo]内容としてはinitなので、別名メソッドとしなくてよいかと
`init(rawValue: RawValue)`

2022-05-09 08:28 UTC, novr commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +        self.weatherRepository.fetchWeather()
[ASK] outputが使われないのは何故でしょうか？

2022-05-09 08:28 UTC, novr commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +        return image.withTintColor(color)
[IMO] O(1)なのでプロパティでもよいかと
また、個別にimageとcolorは使わないのでinitで設定してもよさそうです

2022-05-09 09:18 UTC, daikiumehara commented on Yumemi-ios-training/Enums/Weather.swift
> +    static func create(_ weatherString: String) -> Weather {
Weatherをオプショナルで扱いたくないので、想定外の文字列が渡されたときはnoneで返すという風にしようと思いこのメソッドを作成したんですが、このメソッドはない方が良いでしょうか？

2022-05-09 09:19 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +        self.weatherRepository.fetchWeather()
後から必要になると思い、先に定義しました。
session/3で使用しているので、こちらをみていただけるとありがたいです。🙇‍♂️
https://github.com/daikiumehara/Yumemi-ios-training/pull/3/files#diff-5f741269ab4091f1c3ce54d70701e03557af53847c4cc24637ff616f608b83ee

2022-05-09 09:24 UTC, daikiumehara commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +        return image.withTintColor(color)
プロパティで定義するのは思いつきませんでした！
そのように修正します！

2022-05-09 09:42 UTC, daikiumehara commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +        return image.withTintColor(color)
一点質問です！
O(1)なのでという部分が気になったのですが、
オーダーによってプロパティとメソッドのどちらが適切(メソッドだと計算量が増える、複雑な処理が行われていないことがわかるなど)か、などはあるんでしょうか？

2022-05-09 12:48 UTC, ykws commented on Yumemi-ios-training/View/Main/ViewController.swift
> +protocol MainViewProtocol: NSObjectProtocol {
前のインターン先では Objective-C と Swift 混合のアプリだったか、 Objective-C から移行した名残かもしれませんね。
Swift だけで書く場合は、忘れて良いはずです。

[NSObjectProtocol](https://developer.apple.com/documentation/objectivec/nsobjectprotocol)

2022-05-09 12:49 UTC, ykws commented on Yumemi-ios-training/Client/WeatherClient.swift
> +        return Weather(rawValue: weather)!
現段階では理解して書いてあれば良いと思います！

2022-05-09 12:54 UTC, ykws commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +protocol WeatherUseCaseOutput: NSObjectProtocol {
YAGNI の原則に沿った方が楽できるかなというのと、
この PR でのレビュー対象外の部分はソースコード中にコメント、もしくは PR 上でも良いので、一言添えてあるとレビューの負担が減るので嬉しいです。

2022-05-09 13:38 UTC, ykws reviewed
以降のコミットからで良いですが、

**「レビューをもとに修正を完了しました」** というコミットメッセージだと後でコミットの履歴を見た時になぜ変更したのかわかりづらいので、避けた方が良いです。

レビューで指摘を受けたから対応するのではなく、レビューでの指摘をきっかけに何かしら変更する理由があって変更しているはずなので、その内容を書くとコミット履歴を追う時の助けになります。

またもし、変更する理由がうまく言語化できない場合は、立ち止まってその変更は本当に必要なのか考え直す機会にもなります。あるいは、もう少し踏み込んだ理解が必要な目安にもなり得ると考えています。

2022-05-09 13:38 UTC, ykws commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +    func setOutput(_ output: WeatherUseCaseOutput)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

実装側の class で output を持つことを実質的に強制するので、以下のような宣言の方が明快に思いました。

```suggestion
    var output: WeatherUseCaseOutput? { get set }
```

ただ、この PR で使われないなら削除してしまっても良いかもしれません。

- https://github.com/daikiumehara/Yumemi-ios-training/pull/2#discussion_r867980391
- https://github.com/daikiumehara/Yumemi-ios-training/pull/2#discussion_r867748799

2022-05-09 13:38 UTC, ykws commented on Yumemi-ios-training/Enums/Weather.swift
> +//
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

グループ名 Enums だと何でも放り込めてしまうので、より適切な名前は思いつきそうでしょうか？

2022-05-09 13:38 UTC, ykws commented on Yumemi-ios-training/Environment/Environment.swift
> +struct Environment {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

SwiftUI では [Environment](https://developer.apple.com/documentation/swiftui/environment) が公式に存在するので別の名前の方が驚きが少ないかもです。

2022-05-09 13:38 UTC, ykws commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +extension MainPresenter: WeatherUseCaseOutput {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

不要なら一旦削除しても良いと思いました。

2022-05-09 13:42 UTC, ykws commented on Yumemi-ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +{
対応ばっちりです！

この対応により、画面表示が変わっているので、スクショも撮り直して添付し直してもらえると嬉しいです。

また PR にサイズの大きい画像を添付する時は、

`<img width="320" src="" alt="">` や [table 記法](https://docs.github.com/ja/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables) を利用して並べて表示すると見やすくなるのでさらにレビューがしやすくなります。

2022-05-11 01:06 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +protocol WeatherUseCaseOutput: NSObjectProtocol {
了解しました！
修正しておきます！

2022-05-11 01:25 UTC, daikiumehara commented on Yumemi-ios-training/Enums/Weather.swift
> +//
あまり思い浮かばないのですが、Enumsの下にWeatherディレクトリを作成して、その下にWeather.swiftを入れるというのはどうでしょうか？

2022-05-11 06:10 UTC, novr commented on Yumemi-ios-training/Enums/Weather.swift
> +//
EnumというのはSwift上の型なので、classってディレクトリがあると何用だろうってなりませんか？
階層アーキテクチャ<多層アーキテクチャ>としてディレクトリを分けていると思いますので、何層なのか意識してみるとよいかと

2022-05-11 06:15 UTC, novr commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +        return image.withTintColor(color)
[API GuideLine](https://www.swift.org/documentation/api-design-guidelines/#document-computed-property-complexity)では下記のようにあります
> プロパティアクセスは一般的に計算コストが安価だと見なされるので、そうでない場合はその旨の明記が必要である

以下のような場合は、funcよりpropertyを使う方がよいかと思います
- 例外を投げない
- 計算量がO(1)
- 計算コストが安価(または、最初の呼出し時にキャッシュされる)
- 毎回、同じ結果を返す

2022-05-11 06:21 UTC, novr commented on Yumemi-ios-training/Enums/Weather.swift
> +    static func create(_ weatherString: String) -> Weather {
こんな書き方もできます
```
    init(value: RawValue) {
        self = Weather(rawValue: value) ?? .none
    }
```

2022-05-11 06:28 UTC, daikiumehara commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +        return image.withTintColor(color)
そうなんですね！
気にしたことなかったですが、確かに自分でアクセスする時もpropertyの方が計算コストが安価であるように見えます！
ありがとうございます！🙇‍♂️

2022-05-11 06:29 UTC, novr commented on Yumemi-ios-training/Environment/Environment.swift
> +struct Environment {
役割としてはService LocatorやDI Containerですね
nuits.jp/entry/servicelocator-vs-dependencyinjection

2022-05-11 06:41 UTC, daikiumehara commented on Yumemi-ios-training/Enums/Weather.swift
> +//
Dataの塊なのでDomain層が適切かなと思います。
ModelやEntityのような名前で括ってしまうと、ロジックが含まれていないため個人的には少し違和感を感じるのですが、どうでしょうか？

2022-05-11 06:45 UTC, daikiumehara commented on Yumemi-ios-training/Environment/Environment.swift
> +struct Environment {
そうなんですね！
ありがとうございます！
リンクにアクセスできないのですがどうすればよいでしょうか？

2022-05-11 06:55 UTC, ykws commented on Yumemi-ios-training/Environment/Environment.swift
> +struct Environment {
servicelocator-vs-dependencyinjection で検索すると1件目にヒットすると思います。

2022-05-11 06:59 UTC, daikiumehara commented on Yumemi-ios-training/Environment/Environment.swift
> +struct Environment {
ありがとうございます！
アクセスできました！🙇‍♂️

2022-05-11 08:05 UTC, novr commented on Yumemi-ios-training/Enums/Weather.swift
> +//
はい、Domain層ですね。
ModelやEntityではないのでValueObject相当になると思います

2022-05-11 13:44 UTC, ykws commented on .gitignore
> +*.mmap
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

こちらは意図した変更ですか？

また、この .gitignore はどこか参考にしていたりしますか？

以下などもあったりします。

- [gitignore.ioのススメ](https://qiita.com/dhun/items/adcae139b5ba1da56c81)
- [Swift.gitignore](https://github.com/github/gitignore/blob/main/Swift.gitignore)

2022-05-11 13:44 UTC, ykws commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +    var preconfiguredImage: UIImage {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

名前が重たい感じがするのでいっそ convert の時に `image.withTintColor(color)` した値を `image` として、 WeatherData ではそれだけ持つでも十分かもしれません。

2022-05-12 02:47 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/29793)

2022-05-12 02:47 UTC, novr commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func makeMainPresenter(view: MainViewProtocol) -> MainPresenterProtocol {
[NITS] 内容としてはmakeなんですが、Containerなので外部からの振る舞いとしてはgetが良いかと思います

2022-05-12 04:08 UTC, daikiumehara commented on .gitignore
> +*.mmap
意図した変更ではないです🙇‍♂️
修正します！
このgitignoreはこちらを参考にさせていただきました。
https://qiita.com/ken_sasaki2/items/c3d4faac5253e282c039

2022-05-12 04:13 UTC, daikiumehara commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +    var preconfiguredImage: UIImage {
確かに重く感じますね。
color単体で今後使う可能性があると考えたのですが、現時点で必要ないので消しておいた方がよさそうですね。
修正します！

2022-05-12 04:31 UTC, daikiumehara commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func makeMainPresenter(view: MainViewProtocol) -> MainPresenterProtocol {
了解しました！修正します！

2022-05-12 13:20 UTC, ykws approved these changes
1つ1つのコメントに丁寧に対応ありがとうございました。

![LGTM](https://image.lgtmoon.dev/138714)

以下のコミットのように複数の変更を1つのコミットに混ぜるのは避けましょう。

3e45f88fe1d153b46d674ccb7fadf22ac7ce0206

1つの変更理由で1つのコミットが望ましいです。
そうしておくと、

- 変更差分が読みやすい
- 変更差分が戻しやすい（ revert で戻せるようになります）
- 変更差分を分割しやすい（ rebase, cherry-pick で変更差分を操作しやすくなります）

2022-05-13 04:07 UTC, daikiumehara commented
了解しました！
ありがとうございます！

2022-05-13 05:12 UTC, merged