Session/3
daikiumehara/Yumemi-ios-training pull request #3
Opened 2022-05-06 10:06 UTC by daikiumehara

課題のURL：https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Error.md

# 変更点
・使用するAPIのメソッドの変更
・メソッドの変更に伴い、エラーのハンドリングを記述
・エラー発生時はアラートを表示

## アラート
<img width="400" src="https://user-images.githubusercontent.com/62703773/167111510-148ae38f-97af-434e-a484-2f77a881e200.png">

2022-05-11 04:49 UTC, novr requested changes

2022-05-11 04:49 UTC, novr commented on Yumemi-ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +      "filename" : "iconmonstr-weather-11.pdf",
Vector Data として Single Scale できれいに表示できます
![image](https://user-images.githubusercontent.com/47618299/167770457-065d02ed-9a1f-46a1-9b34-67646f407e65.png)

2022-05-11 04:49 UTC, novr commented on Yumemi-ios-training/Client/WeatherClient.swift
> +        return Weather(rawValue: weather)!
!に失敗する場合はunexpectedやunknownなどのエラーではないですか？

2022-05-11 04:49 UTC, novr commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +class MainPresenter: NSObject, MainPresenterProtocol {
[ASK] NSObjectの継承は何故必要でしょうか？

2022-05-11 05:03 UTC, daikiumehara commented on Yumemi-ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +      "filename" : "iconmonstr-weather-11.pdf",
session2で修正済みです。
session2をmergeしてrebaseした際に修正します。

2022-05-11 05:11 UTC, daikiumehara commented on Yumemi-ios-training/Client/WeatherClient.swift
> +        return Weather(rawValue: weather)!
現時点で想定外の値が返ってくることはないため、force unwrappingしています。
APIから取得するデータが間違っている可能性がある場合はforce unwrappingではなく、optional unwrapping、エラーのthrowを用いるのが適切だと考えました。

2022-05-11 14:27 UTC, ykws requested changes
コンフリクトしているので rebase をお願いします。

2022-05-12 05:50 UTC, daikiumehara commented
rebaseしてforce pushしました

2022-05-12 15:23 UTC, novr commented on Yumemi-ios-training.xcodeproj/xcuserdata/d_umehara.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
.gitignoreにいれても、一度addされてしまうと管理対象なので
`git rm`が必要な場合があります

2022-05-12 15:24 UTC, novr commented on Yumemi-ios-training/Mapper/Generator/ErrorAlertGenerator.swift
> +    static func geenrate(messsage: String) -> UIAlertController {
typo
```suggestion
    static func generate(message: String) -> UIAlertController {
```

2022-05-12 15:27 UTC, novr commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +    func happendError(error: String)
typo
```suggestion
    func happenedError(error: String)
```

2022-05-13 04:45 UTC, daikiumehara commented on Yumemi-ios-training/Client/WeatherClient.swift
> +    static func fetctWeather(jsonString: String) throws -> String {
すいません。session4の内容が混ざっていたので、不必要なコミットを削除しました🙇‍♂️

2022-05-13 04:57 UTC, daikiumehara commented on Yumemi-ios-training.xcodeproj/xcuserdata/d_umehara.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
一度キャッシュを消してから、再度追加してみました。
確認お願いします🙇‍♂️

2022-05-13 04:59 UTC, daikiumehara commented on Yumemi-ios-training/Mapper/Generator/ErrorAlertGenerator.swift
> +    static func geenrate(messsage: String) -> UIAlertController {
そのような機能があるのですね！
修正します！

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +    func fetchWeather(at: String) -> Result<Weather, APIError> {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

func 内の変数名が `at` だと何のことか分かりづらいので、以下も参考に名前を付けておきましょう。

> `static func fetchWeather(at area: String) throws -> String`
>
> https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Error.md

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/Model/APIError.swift
> +    var text: String {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

[LocalizedError](https://developer.apple.com/documentation/foundation/localizederror) に準拠するのもおすすめです。

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
>  protocol WeatherUseCaseProtocol {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

```suggestion
protocol WeatherUseCaseProtocol: AnyObject {
```

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +    func setOutput(_ output: WeatherUseCaseOutput)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

https://github.com/daikiumehara/Yumemi-ios-training/pull/2#discussion_r867989293

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/Mapper/Generator/ErrorAlertGenerator.swift
> +    static func generate(message: String) -> UIAlertController {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

generate は柔らかいもの（乱数など）を生成するイメージで、
UI のパーツを組み立ているので build のイメージです。

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +        }
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

こう書くこともできます。

```suggestion
        } catch let error as YumemiWeatherError {
            switch error {
            case .invalidParameterError:
                return .failure(.invalidParameter)
            case .unknownError:
                return .failure(.unknown)
            }
        } catch {
            return .failure(.unexpected)
        }
```

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/Model/WeatherInfo.swift
> +    let minTemp: Int
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

まだ Session3 では使わないですかね

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/Model/APIError.swift
> +        case .unexpected: return "予想外のエラーが発生しました"
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

定義順と順番が揃っていると驚きが少ないです。

2022-05-13 14:42 UTC, ykws commented on Yumemi-ios-training/Client/WeatherClient.swift
> +    static func fetchWeather(at: String) throws -> Weather {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

こちらも func 内の変数名が `at` だと何のことか分かりづらいので、以下も参考に名前を付けておきましょう。

> `static func fetchWeather(at area: String) throws -> String`
>
> https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Error.md

2022-05-16 01:51 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +    func fetchWeather(at: String) -> Result<Weather, APIError> {
了解しました！
修正しました！

2022-05-16 02:09 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +    func setOutput(_ output: WeatherUseCaseOutput)
修正しました！

2022-05-16 02:10 UTC, daikiumehara commented on Yumemi-ios-training/Mapper/Generator/ErrorAlertGenerator.swift
> +    static func generate(message: String) -> UIAlertController {
メソッド名をbuildに変更する場合、GeneratorからBuilderのように変更する必要があるのでしょうか？

2022-05-16 02:17 UTC, daikiumehara commented on Yumemi-ios-training/Client/WeatherClient.swift
> +    static func fetchWeather(at: String) throws -> Weather {
修正しました！

2022-05-16 02:17 UTC, daikiumehara commented on Yumemi-ios-training/Model/APIError.swift
> +        case .unexpected: return "予想外のエラーが発生しました"
修正しました！

2022-05-16 02:19 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +        }
書き方勉強のために修正しました！

2022-05-16 02:53 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
>  protocol WeatherUseCaseProtocol {
修正しました！

2022-05-16 02:53 UTC, daikiumehara commented on Yumemi-ios-training/Model/WeatherInfo.swift
> +    let minTemp: Int
ファイルを削除しました！

2022-05-16 03:20 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/19352)

2022-05-16 05:03 UTC, merged

2022-05-16 11:39 UTC, ykws commented on Yumemi-ios-training/Mapper/Generator/ErrorAlertGenerator.swift
> +    static func generate(message: String) -> UIAlertController {
そうですね。 Builder が build する。 Generator が generate するのが驚きが少ないです。

2022-05-17 18:36 UTC, daikiumehara commented on Yumemi-ios-training/Mapper/Generator/ErrorAlertGenerator.swift
> +    static func generate(message: String) -> UIAlertController {
mergeしてしまったのでセッション4で修正します！