セッション4
daikiumehara/Yumemi-ios-training pull request #4
Opened 2022-05-09 06:35 UTC by daikiumehara

課題のURL：https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Json.md

# 変更点
・最高気温、最低気温が表示されるようになりました

## UIの変更
![Simulator Screen Shot - iPod touch (7th generation) - 2022-05-09 at 15 32 11](https://user-images.githubusercontent.com/62703773/167353077-d110a6bb-6489-4eb4-82c9-084944f35514.png)
。

2022-05-11 02:43 UTC, daikiumehara commented
テスト

2022-05-11 14:27 UTC, ykws requested changes
コンフリクトしているので rebase をお願いします。

2022-05-12 13:30 UTC, ykws requested changes
こちらも session/3 を rebase しているので、 session/2 の変更内容が反映で規定なさそうです。

2022-05-16 12:07 UTC, ykws reviewed
convert の数が扱っている内容に反して多すぎるのが負担になっているように感じました。
全体的に薄くなるように見直しても良いかもしれません。

現状維持するなら、何から何に変換しているのか意識して、各引数名（data, info, weather など）を揃えてもらえると読みやすくなると思いました。

2022-05-16 12:07 UTC, ykws commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +        self.view?.changeWeather(data: WeatherConverter.convert(data: weather))
素直に読むと、
changeWeather に data を渡すために、 data として weather を渡して Weather に convert してる
と読めてしまうので、非常に難解になっていると感じました。

2022-05-16 12:07 UTC, ykws commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            guard let data = try WeatherClient.fetchWeather(jsonString: jsonString).data(using: .utf8) else {
do-catch が入れ子になってしまっているのは可能なら避けたいのと、
fetch と encode が1行に混ざっていると分けて書くと整理しやすいかなと思いました。

2022-05-17 18:45 UTC, daikiumehara commented on Yumemi-ios-training/InfraObject/InfraWeatherInfo.swift
> +    private enum CodingKeys: String, CodingKey {
そうなんですね！
修正しました！

2022-05-17 18:54 UTC, daikiumehara commented on Yumemi-ios-training/Model/SearchParameter.swift
> +struct SearchParameter: Encodable {
修正しました！

2022-05-17 18:56 UTC, daikiumehara commented on Yumemi-ios-training/InfraObject/InfraWeatherInfo.swift
> +    let weather: String
enumをCodable対応させれるのは知りませんでした！
修正しました！

2022-05-17 19:04 UTC, daikiumehara commented on Yumemi-ios-training/Mapper/Converter/WeatherConverter.swift
>  struct WeatherConverter {
修正しました！

2022-05-17 19:06 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +                return .success(WeatherInfoConverter.convert(data: info))
修正しました！

2022-05-17 19:08 UTC, daikiumehara commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +    let imageData: WeatherImageData
WeatherImageDataのプロパティが減ったため、UIImageのみでよさそうですね！
修正します！

2022-05-17 19:14 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +    func fetchWeather(params: SearchParameter) -> Result<WeatherInfo, APIError>
確かにおかしいですね！
修正しました！

2022-05-17 19:17 UTC, daikiumehara commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +        self.view?.changeWeather(data: WeatherConverter.convert(data: weather))
なるほどです！
仮引数名をUIDataのように変更すると少しはわかりやすくなるでしょうか？

2022-05-18 02:21 UTC, ykws commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +                                     date: "2020-04-01T12:00:00+09:00")
こういうのがあります。 

[dateEncodingStrategy](https://developer.apple.com/documentation/foundation/jsonencoder/2895363-dateencodingstrategy)

2022-05-18 02:25 UTC, ykws commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +        self.view?.changeWeather(data: WeatherConverter.convert(data: weather))
そうですね。まずは型と仮引数名は合わせて、何から何に変換しているのか明確にしてもらえると読みやすくなると思いました。

2022-05-18 02:45 UTC, ykws commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            guard let data = try WeatherClient.fetchWeather(jsonString: jsonString).data(using: .utf8) else {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

こういうイメージです。
何を扱っているのか一つずつ丁寧に書いていくと良いと思いました。

```suggestion
            guard let weather = try WeatherClient.fetchWeather(jsonString: jsonString),
                  let data = weather.data(using: .utf8) else {
```

2022-05-18 04:55 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +                                     date: "2020-04-01T12:00:00+09:00")
ありがとうございます！
UseCaseからDate型で渡すことができました！
修正しました！

2022-05-18 05:02 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            guard let data = try WeatherClient.fetchWeather(jsonString: jsonString).data(using: .utf8) else {
了解しました！
修正します！

2022-05-19 05:36 UTC, ykws commented on Yumemi-ios-training/UIModel/WeatherData.swift
>  import Foundation
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

UIKit を import したら Foundation の import を省略できます。

2022-05-19 05:36 UTC, ykws commented on Yumemi-ios-training/Mapper/Converter/WeatherDataConverter.swift
> +    static func convert(info: WeatherInfo) -> WeatherData {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

WeatherInfo と WeatherData の Info と Data はどういう意図で使い分けていますか？
また Info の Infra とそうでないものも
それらの区別に対して今ついている名前だと意図が掴みにくいのでより明快な名前が欲しいと思いました。
名前を付けづらいとしたら、もしかしたら責務がうまく分けれていないかもです。

2022-05-19 05:36 UTC, ykws commented on Yumemi-ios-training/Model/APIError.swift
> +        case .missEncode: return "エンコードに失敗しました"
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

宣言順になっていると驚きが少ないです。

2022-05-19 05:36 UTC, ykws commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            } else {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

他と揃えて、 guard で failure を返したいです。

2022-05-19 05:36 UTC, ykws commented on Yumemi-ios-training/UIModel/WeatherImageData.swift
> +struct WeatherImageData {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

不要になっていれば削除して良さそうです。

2022-05-19 05:36 UTC, ykws commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            self.output?.changeWeather(info: weather)
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

この辺りも info なのか weather なのか統一できると良いです

2022-05-19 05:36 UTC, ykws commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +    func changeWeather(info: WeatherInfo)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

weatherInfo と省略せずに表現してみると良いと思います。

2022-05-19 05:36 UTC, ykws commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            if let info = try? decoder.decode(InfraWeatherInfo.self,
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

この後のコードで WeatherInfo に変換するので、それと区別するために InfraWeatherInfo と命名しておくと驚きが少ないです。

2022-05-19 07:24 UTC, daikiumehara commented on Yumemi-ios-training/Mapper/Converter/WeatherDataConverter.swift
> +    static func convert(info: WeatherInfo) -> WeatherData {
確かに少しわかりづらいですね。
僕の中では、WeatherInfoは純粋なData、WeatherDataはUI用のDataという位置付けでした。
WeatherDataをWeatherUIDataに修正します！

2022-05-19 07:36 UTC, daikiumehara commented on Yumemi-ios-training/Model/APIError.swift
> +        case .missEncode: return "エンコードに失敗しました"
同じミスをすいません。
修正しました!

2022-05-19 07:37 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            } else {
修正しました！

2022-05-19 07:38 UTC, daikiumehara commented on Yumemi-ios-training/UIModel/WeatherImageData.swift
> +struct WeatherImageData {
修正しました！

2022-05-19 07:47 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            self.output?.changeWeather(info: weather)
修正しました！

2022-05-19 07:55 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            if let info = try? decoder.decode(InfraWeatherInfo.self,
修正しました！

2022-05-19 12:06 UTC, ykws approved these changes
対応ありがとうございました。
後は細かいところなので、次のセッションや別途 Issue を立てて対応とかでも良いと思いました。

![LGTM](https://image.lgtmoon.dev/125336)

一つの変更に対して、影響範囲が大きくなっているので、
適切なアーキテクチャを選択する難しさが体感できたのではないかと思います。
（この PR は二つの Session の変更が混ざっているので大きくなっている側面もありますが）

責務を分割せずに単にバケツリレーするだけだと、却って変更が大変になり、また可読性も損なわれるので、薄くできる部分は薄くできると良いと思いました。

2022-05-20 02:26 UTC, merged

2022-05-20 02:27 UTC, daikiumehara commented
了解しました！
ありがとうございます！