セッション6
daikiumehara/Yumemi-ios-training pull request #5
Opened 2022-05-11 02:06 UTC by daikiumehara

課題のURL：https://github.com/yumemi-inc/ios-training/blob/main/Documentation/VC_Lifecycle.md

# 変更点
・起動時の画面を変更
・起動画面表示時に元々作成していた画面に遷移
・closeボタンを押下したときに、ViewControllerを閉じる

## 実行時の様子
https://user-images.githubusercontent.com/62703773/167754013-2ee116f2-446f-4c4b-98d0-0804bcdd5f96.mov

2022-05-11 13:55 UTC, ykws commented on Yumemi-ios-training/View/Launch/LaunchViewController.swift
> +            print("VCが見つかりませんでした。")
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

開発中に検知されるべきなので fatalError や force unwrapping でも良さそうです。

2022-05-11 13:55 UTC, ykws commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.presenter?.onTapResetButton()
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

Presenter 側が Reset になっているのは何か理由があったりしますか？

またこの部分で Presenter を経由することでどんな課題を解決していると考えますか？

もし Presenter を経由しないとどうなるでしょうか？

2022-05-12 04:34 UTC, daikiumehara commented on Yumemi-ios-training/View/Launch/LaunchViewController.swift
> +            print("VCが見つかりませんでした。")
アプリをクラッシュさせるのでも問題なさそうなのでそのように修正しておきます！

2022-05-12 05:03 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.presenter?.onTapResetButton()
命名はミスでした。修正します！
現時点で経由しているメリットはアーキテクチャに乗っ取っているという点(Viewにロジックを持たせない)であると考えています。
Presenterを経由しないとCloseボタンが押された際、処理内容を変更する時にロジックを持たないはずのVIewを変更しないといけなくなってしなうと考えています。

2022-05-12 13:50 UTC, ykws commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.presenter?.onTapResetButton()
なるほどです。
処理内容を変更するときに Presenter を経由するように変更すれば良いと思います。

現状は Presenter が View に強く依存した命名になっているので、
Presenter は View のイベントや Ui パーツには依存せず、任意のタイミングで実行されて良い処理を提供し、 View はそれを呼ぶだけにすると関心の分離ができると思いました。

例えばですが、実際に CloseButton が ResetButton に変更になった場合、
現状は View と Presenter を命名の関係で両方変更が必要ですが、この場合は View だけ変更されるのが望ましいです。
Presenter の公開する名前としては、 onTap も CloseButton も入っていないと変更の必要がなくなるので嬉しいです。

2022-05-13 06:06 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.presenter?.onTapResetButton()
なるほどです！
確かにUIパーツの名前変更だけでPresenterを変更しないといけないのは良くないですね。

2022-05-13 11:23 UTC, daikiumehara commented
rebaseしてforce pushしました

2022-05-13 14:50 UTC, ykws commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.presenter?.onTapResetButton()
そうですね。 dismiss するだけなので、 Presenter を経由せずに View で処理して良いと考えます。
単一データフローを意識して、全て Action として処理するという考えも、勿論あるので、 Flux をキーワードに調べてみてください。

2022-05-13 14:55 UTC, ykws reviewed
645cc61bfa93c6e300c4701a8181a40d4287205c このコミットから Session6 の対応だと思うので、まだ rebase の必要がありそうです。
先に #4 の rebase を解決しないと、この branch が #4 の方を参照しているので、対応後に再対応が必要になる可能性が高いです。
rebase の解消は古い部分から進めていくのが手戻りが少なくなります。

2022-05-20 06:10 UTC, novr commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +        if let yumemiWeatherError = error as? YumemiWeatherError {
[IMO] 以下のように書けます
```
switch
  case let error as YumemiWeatherError:
    ~
```

2022-05-20 06:19 UTC, daikiumehara commented on Yumemi-ios-training/Mapper/Converter/WeatherConverter.swift
> +struct WeatherConverter {
修正しました！

2022-05-20 06:19 UTC, daikiumehara commented on Yumemi-ios-training/Model/SearchParameter.swift
> +struct SearchParameter: Encodable {
修正しました！

2022-05-20 06:19 UTC, daikiumehara commented on Yumemi-ios-training/Model/APIError.swift
> +        case .missEncode: return "エンコードに失敗しました"
修正しました！

2022-05-20 06:25 UTC, daikiumehara commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +        let weatherUIData = WeatherUIDataConverter.convert(weatherInfo: weatherInfo)
ModelからUIModelに変換する際、処理が複雑に可能性を考えて全てをConverterを経由して作成する形を取っているのですが、あまり適切ではないでしょうか？

2022-05-20 06:29 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +        if let yumemiWeatherError = error as? YumemiWeatherError {
修正しました！

2022-05-23 06:15 UTC, ykws requested changes
rebase が適用されていない箇所があるようなので、確認をお願いします。

2022-05-23 06:15 UTC, ykws commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +        let weatherUIData = WeatherUIDataConverter.convert(weatherInfo: weatherInfo)
処理が複雑になった時に変えていけば良いと思います。
以下でもコメントしましたが、現状は、層が厚くなっているので、単純な処理に対して、可能な限り薄くするのがより適切だと私も思いました。

https://github.com/daikiumehara/Yumemi-ios-training/pull/4#pullrequestreview-978435895

2022-05-23 06:15 UTC, ykws commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +    let imageData: WeatherImageData
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

rebase が適用されていないですか？

1d952c0854c15ea507eced65262f5b3b1d81e8d2

2022-05-23 06:15 UTC, ykws commented on Yumemi-ios-training/UIModel/WeatherImageData.swift
> +struct WeatherImageData {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

この辺りも rebase が適用されていないですか？

c6d7a239b396d111420e1ee3a2f89a0af3bf95d0

2022-05-23 06:28 UTC, daikiumehara commented on Yumemi-ios-training/UIModel/WeatherData.swift
> +    let imageData: WeatherImageData
修正しました！

2022-05-23 06:28 UTC, daikiumehara commented on Yumemi-ios-training/UIModel/WeatherImageData.swift
> +struct WeatherImageData {
修正しました！

2022-05-23 07:51 UTC, daikiumehara commented on Yumemi-ios-training/Presenter/MainPresenter.swift
> +        let weatherUIData = WeatherUIDataConverter.convert(weatherInfo: weatherInfo)
修正しました！

2022-05-24 00:52 UTC, novr commented on Yumemi-ios-training/View/Main/ViewController.swift
> +    func inject(presenter: MainPresenterProtocol)
[IMO] viewの振る舞いに対してinjectする事はないですよね？

2022-05-25 01:21 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/ViewController.swift
> +    func inject(presenter: MainPresenterProtocol)
テストをする際にMockを注入しやすいようにinjectメソッドを定義したのですが、必要ないということでしょうか？

2022-05-25 04:03 UTC, novr commented on Yumemi-ios-training/View/Main/ViewController.swift
> +    func inject(presenter: MainPresenterProtocol)
MainViewProtocolに対して、injectを呼び出す事はないですよね
テストにおいても、MainViewProtocolに対してmockを注入する事はないかと思います

2022-05-25 04:35 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/ViewController.swift
> +    func inject(presenter: MainPresenterProtocol)
確かにProtocolに定義するメソッドではないですね。
修正します！

2022-05-25 12:03 UTC, ykws requested changes
ViewController の命名だけ must で直してもらえればと思います。

他は別途でも大丈夫だと思います。

2022-05-26 01:57 UTC, daikiumehara commented on Yumemi-ios-training/View/Launch/LaunchViewController.swift
> +class LaunchViewController: UIViewController {
修正しました！

2022-05-26 01:57 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/ViewController.swift
> +    func inject(presenter: MainPresenterProtocol) {
修正しました！

2022-05-26 01:57 UTC, daikiumehara commented on Yumemi-ios-training/View/Launch/LaunchViewController.swift
> +        let mainVC = ViewController.instantiate()
修正しました！

2022-05-26 02:00 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.presenter?.closeAction()
修正しました！

2022-05-26 02:07 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.dismiss(animated: true)
修正しました！

2022-05-26 13:29 UTC, ykws commented on Yumemi-ios-training/View/Launch/LaunchViewController.swift
> +        let mainVC = ViewController.instantiate()
✅ 8dafa218d65bcab7305baaa34424e0fe56994e1b

2022-05-26 13:40 UTC, ykws commented on Yumemi-ios-training/View/Main/WeatherViewController.swift
> +    var presenter: WeatherPresenterProtocol?
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

https://github.com/daikiumehara/Yumemi-ios-training/pull/5#discussion_r881548012

このコメントで言いたかった Implicitly Unwrapped Optionals はこの宣言時の方でした。

```suggestion
    var presenter: WeatherPresenterProtocol!
```

2022-05-26 13:40 UTC, ykws commented on Yumemi-ios-training/View/Main/WeatherViewController.swift
> +        self.presenter!.closeAction()
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

Implicitly Unwrapped Optionals で宣言しておくと Forced Unwrapping が不要になります。

```suggestion
        self.presenter.closeAction()
```

2022-05-26 13:40 UTC, ykws commented on Yumemi-ios-training/View/Main/WeatherViewController.swift
> +        super.viewDidLoad()
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

super を呼ぶだけなら消しても大丈夫です。

2022-05-26 13:40 UTC, ykws commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.dismiss(animated: true)
修正したコミットが push されていないようでした。

2022-05-26 17:45 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/WeatherViewController.swift
> +    var presenter: WeatherPresenterProtocol?
すいません！
のちに気づいて修正したのですが、pushし忘れていたみたいです！
pushしました！

2022-05-26 17:49 UTC, daikiumehara commented on Yumemi-ios-training/View/Main/WeatherViewController.swift
> +        super.viewDidLoad()
修正しました！

2022-05-27 13:52 UTC, ykws commented on Yumemi-ios-training/View/Main/ViewController.swift
> +        self.dismiss(animated: true)
✅ 3787dfc6376dd6cb49b878d9d5c1d8c78ef5029c

2022-05-29 07:45 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/6274)

2022-05-30 02:36 UTC, merged