セッション8
daikiumehara/Yumemi-ios-training pull request #7
Opened 2022-05-12 11:59 UTC by daikiumehara

課題のURL：https://github.com/yumemi-inc/ios-training/blob/main/Documentation/UnitTest.md

# 変更点
テストを記述しました

2022-05-12 14:13 UTC, ykws requested changes
rebase がうまくいっていないですが、テストコードの部分だけコメントしました。

2022-05-12 14:13 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +            let weatherData = WeatherConverter.convert(data: data)
![must-badge](https://img.shields.io/badge/review-must-red.svg)

ViewController に Mock を注入しているので、 `onTapReloadButton` を実行して期待した結果になるか検証してみましょうか。

2022-05-12 14:13 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        testList.forEach { data in
![must-badge](https://img.shields.io/badge/review-must-red.svg)

仮にテストの途中で失敗することがあると、残りのテストが実行されないため、
1つのテストで1つの func を用意してみましょうか。

テスト func には日本語で命名する慣習もあるので、以下のように用意してみましょうか。

- test_天気予報がsunnyだったら_画面に晴れ画像が表示されること
- test_天気予報がcloudyだったら_画面に曇り画像が表示されること
- test_天気予報がrainyだったら_画面に雨画像が表示されること
- test_天気予報の最高気温がUILabelに反映されること
- test_天気予報の最低気温がUILabelに反映されること

2022-05-12 14:13 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +            XCTAssertEqual(vc.weatherImageView.image!, weatherData.imageData.createImage())
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

テストなので、なるべく余計なロジックを排除して期待する結果と比較する方が紛れが少ないです。

2022-05-13 06:42 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +            let weatherData = WeatherConverter.convert(data: data)
了解しました！

2022-05-13 06:42 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        testList.forEach { data in
そうなんですね！
修正します！

2022-05-13 09:22 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +            XCTAssertEqual(vc.weatherImageView.image!, weatherData.imageData.createImage())
了解しました！
修正しました！

2022-05-13 12:19 UTC, daikiumehara commented
rebaseしてforce pushしました

2022-05-20 06:27 UTC, novr requested changes

2022-05-20 06:27 UTC, novr commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
>      func testExample() throws {
内容がないテストは削除しちゃってOKです

2022-05-20 06:27 UTC, novr commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTAssertEqual(vc.weatherImageView.image!, weatherData.imageData.createImage())
[IMO] テストの対象がはっきりしません
MockMainPresenter.changeWeatherを経由したViewControllerのテスト？

`天気予報がsunnyだったら_画面に晴れ画像が表示されること`ならば、`changeWeather(data:)`を呼べばいいのでpresenterを経由する必要がないです

2022-05-20 06:27 UTC, novr commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTAssertEqual(vc.weatherImageView.image!, weatherData.imageData.createImage())
[IMO] 複数のテストコンテキストが混ざってしまっています
`onTapReloadButton`が発生したときに、ViewControllerの`changeWeather(data:)`が呼ばれて画像が設定されることは結合テストになり、presenterをmockにしてしまうとmockのテストになってしまいます

2022-05-20 06:44 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
>      func testExample() throws {
修正しました！

2022-05-20 06:47 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTAssertEqual(vc.weatherImageView.image!, weatherData.imageData.createImage())
https://github.com/daikiumehara/Yumemi-ios-training/pull/7#discussion_r877775537
こちらのコメントと合わせての質問になるのですが、この部分で必要なテストはViewControllerのchangeWeatherを直接呼び出し、表示されている画像が正しいかを調べるだけで良いということでしょうか？

2022-05-25 12:26 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTAssertEqual(vc.weatherImageView.image!, weatherData.imageData.createImage())
@daikiumehara @novr 
申し訳ありません。これは自分の理解が違っていました。

https://github.com/daikiumehara/Yumemi-ios-training/pull/7#discussion_r871431008

また前述の方法でテストするなら、今の構成だと Client があるので、 Presenter ではなく、 Clinet の Stub を用意し、任意のデータを返してもらってテストしたいです。

- [【テスト駆動開発】スタブ、モック、フェイク、ダミーの違いとは?](https://craftsman-software.com/posts/38)

2022-05-26 06:00 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTAssertEqual(vc.weatherImageView.image!, weatherData.imageData.createImage())
@ykws @novr 
Clientのstubを作成する形に変更してみました！
確認お願いします！

2022-05-26 14:05 UTC, ykws reviewed
層が厚くてテストを書くのが難しいと感じたら、
一度 View-Model のシンプルな構成に立ち戻っても良いかもしれません。

セッション8 の内容を見直してみてください。
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/UnitTest.md

2022-05-26 17:51 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Mock/MockMain.swift
> +import Foundation
不要なので削除しました！

2022-05-26 18:06 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Mock/MockWeatherClient.swift
> +final class MockWeatherClient: WeatherClientProtocol {
そうなんですね。ありがとうございます！
修正しました！

2022-05-26 18:35 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Mock/MockWeatherPresenter.swift
> +final class MockWeatherPresenter: WeatherPresenterProtocol {
presenter、UseCase間がDelegateで通知される仕組みになっているため、`XCTestExpectation`を使用して、通知されるタイミングまで待たないとimageViewなどに画像が設定される前にアクセスしてしまい、正しくテストを行うことができないため、MockWeatherPresenterを作成する必要がありました。
`XCTestExpectation`を使用しない形で書く方法がありましたら教えていただきたいです。

2022-05-30 11:36 UTC, daichikuwa0618 commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +        return self.weatherClient.fetchWeather()
[FYI]
```suggestion
        weatherClient.fetchWeather()
```

1 行の return は省略できますのでご参考までに。

2022-05-30 11:36 UTC, daichikuwa0618 commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            let infraWeatherInfo = try self.weatherClient.fetchWeather(jsonString: jsonString)
[nits, imo]
上もそうですが、 clusure とかでなければ省略できる self は省略しちゃっていいように思います。

2022-05-30 11:36 UTC, daichikuwa0618 commented on Yumemi-ios-trainingTests/Mock/MockDIContainer.swift
> +struct MockDIContainer {
[ask]
`getMockWeatherPresenter` と同じことを `setupWithError` でやる方法ではだめでしょうか？

[FYI]
`static func` にしていますが、単純に namespace を用意したいだけであれば `enum` を使うと変にインスタンス作れないので便利です。

2022-05-30 11:36 UTC, daichikuwa0618 commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        wait(for: [exp], timeout: 5.0)
[ask]
同期処理だけで構成されていると思ったのですが、 `XCTestExpectation` による待ちが必要でしょうか？

2022-05-30 11:36 UTC, daichikuwa0618 commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTestExpectation(description: "\(funcName)のタイムアウト")
[nits]
```suggestion
    private func makeExpectation(_ funcName: String) -> XCTestExpectation {
        XCTestExpectation(description: "\(funcName)のタイムアウト")
```

のほうが良さそうです。

2022-05-30 14:06 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Mock/MockDIContainer.swift
> +struct MockDIContainer {
> getMockWeatherPresenter と同じことを setupWithError でやる方法ではだめでしょうか？

別のテストで使用することもなさそうなのでその方法が良いですね！
修正します！

2022-06-01 05:48 UTC, ykws commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            let infraWeatherInfo = try self.weatherClient.fetchWeather(jsonString: jsonString)
> 変数のスコープがわかりやすい

これはその通りだと思います。

ただし、変数のスコープを気にするというのは、コードが複雑になっている兆候かもしれなくて、
言語仕様として用意されている簡潔な表現で意図が明確に伝わるなら、可読性が向上すると感じています。

可読性のもう一つの観点としては、一貫性があって、一貫して付与してあるなら方針としてはありだと思います。

2022-06-01 06:03 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTestExpectation(description: "\(funcName)のタイムアウト")
get の場合、既に生成されているものを取得することを期待し、
make の場合、何か生成されることを期待します。

2022-06-01 06:21 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            let infraWeatherInfo = try self.weatherClient.fetchWeather(jsonString: jsonString)
セッション8で修正すると、コンフリクトがすごくなりそうなので別のセッションで修正します

2022-06-01 07:37 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Mock/MockWeatherPresenter.swift
> +final class MockWeatherPresenter: WeatherPresenterProtocol {
再度書き直してみると問題なく動いたので修正しました！

2022-06-02 13:45 UTC, ykws reviewed
だいぶすっきりしてきたと思います。
セルフレビューでコメントした観点に自分で気づけるとさらに Good です！

簡潔に表現できる箇所や、不要になっているコード・差分があるため、見直してみてください。

2022-06-02 13:45 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    private func makeExpectation(_ funcName: String) -> XCTestExpectation {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

不要になっているはずです！

2022-06-02 13:45 UTC, ykws commented on Yumemi-ios-trainingTests/Mock/MockWeatherPresenter.swift
> +final class MockWeatherPresenter: WeatherPresenterProtocol {
こちらも不要になっているはずです！

2022-06-02 13:45 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTAssertEqual(vc.minTempLabel.text!, weatherUIData.minTemp)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

テストコードで期待する結果は直値で表現する方が安心だったりします。
各変換の過程で不備があった場合に原因の特定が面倒になるため、このように書くなら、 Converter のテストも書いておくと安心です。

あと forced unwrapping はなくても大丈夫なはずです。

```suggestion
        XCTAssertEqual(vc.minTempLabel.text, "5")
```

2022-06-02 13:45 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        let weatherUIData = WeatherUIData(weatherInfo: weatherInfo)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

テストコードで期待値を直値で表現したら、この辺りも不要になります。

2022-06-02 13:45 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: WeatherPresenterProtocol!
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

ここも使っていないはずです。

2022-06-02 13:45 UTC, ykws commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func makeWeatherUseCase(weatherRepository: WeatherRepositoryProtocol) -> WeatherUseCaseProtocol {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

外部公開しないで済んでいるので private のままで良いはずです。

2022-06-02 13:45 UTC, ykws commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func makeWeatherRepository(weatherClient: WeatherClientProtocol) -> WeatherRepositoryProtocol {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

こちらも private のままで。

2022-06-02 13:45 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        weatherClient = StubWeatherClient()
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

WeatherViewController と WeatherClient は宣言時に生成して使いまわしても良さそうです。

2022-06-03 04:46 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    private func makeExpectation(_ funcName: String) -> XCTestExpectation {
修正しました！

2022-06-03 04:50 UTC, daikiumehara commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func makeWeatherUseCase(weatherRepository: WeatherRepositoryProtocol) -> WeatherUseCaseProtocol {
修正しました！

2022-06-03 04:50 UTC, daikiumehara commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func makeWeatherRepository(weatherClient: WeatherClientProtocol) -> WeatherRepositoryProtocol {
修正しました！

2022-06-03 04:54 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        weatherClient = StubWeatherClient()
修正しました！

2022-06-03 04:55 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: WeatherPresenterProtocol!
修正しました！

2022-06-03 05:12 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        let weatherUIData = WeatherUIData(weatherInfo: weatherInfo)
修正しました！

2022-06-03 05:12 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        XCTAssertEqual(vc.minTempLabel.text!, weatherUIData.minTemp)
修正しました！

2022-06-03 14:38 UTC, ykws reviewed
テストは良さそうなのですが、 gitignore が気になったので確認をお願いします。

2022-06-03 14:38 UTC, ykws commented on .gitignore
> +xcshareddata
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

これを追加した理由とかありますか？

合わせて 656684d0a2c2420c33d14dca77fe4339fe633680 にて削除したファイルはリポジトリで管理するのが通例です。

2022-06-06 07:29 UTC, daichikuwa0618 reviewed
expectation 無くせたようで良かったです。正直かなりいい感じなのですが、ここまで来たので違和感あるところをコメントしました。

2022-06-06 07:29 UTC, daichikuwa0618 commented on Yumemi-ios-training/Client/WeatherClient.swift
> +final class WeatherClient: WeatherClientProtocol {
`final` を自然に付けられていて良いと思います 💯

2022-06-06 07:29 UTC, daichikuwa0618 commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func getWeatherPresenter(view: WeatherViewProtocol, weatherClient: WeatherClientProtocol) -> WeatherPresenterProtocol {
[imo]
DI container っていうのは依存関係を解決するために注入するものを置く場所なので、ここに引数が追加されて外からさらに依存関係を注入できるのは違和感を感じます。
なんなら DI container の外部アクセスはメソッドではなく `lazy var` プロパティでも良いんじゃないでしょうか。

DI container で依存関係は閉じておいて、外からは使いたいオブジェクトを参照するだけという作りではどうでしょう？

また、引数が追加された背景としてはテストのための stub オブジェクトを注入したいというのが背景にあるのかなと妄想しますが、それはテストコードの中で DI container を介さずに依存関係を解決していくっていうので実現できるかと思います。

2022-06-06 07:58 UTC, daikiumehara commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func getWeatherPresenter(view: WeatherViewProtocol, weatherClient: WeatherClientProtocol) -> WeatherPresenterProtocol {
そうですね。
僕自身もDIContainer外から受け取るプロパティは必要最低限で実装したいなという考え方です。
DIContainerに対する考え方によってコードが変わってくると思うのですが、
このようなレビュワーの方の考え方が複数ある場合はどのように修正するべきでしょうか？

2022-06-06 14:16 UTC, ykws requested changes
エラーハンドリングの部分が変わってしまっていたので、確認をお願いします。

2022-06-06 14:16 UTC, ykws commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func getWeatherPresenter(view: WeatherViewProtocol, weatherClient: WeatherClientProtocol) -> WeatherPresenterProtocol {
ここの役割としては Container ではなく、 Builder なのではと思いました。

> このようなレビュワーの方の考え方が複数ある場合はどのように修正するべきでしょうか？

must ではない場合は、 PR 作者がフィードバックを受けて判断してもらえればと思います。
もし must で意見が対立するようなことがあれば、レビュワー同士で解決してもらう必要があると思います。

2022-06-06 14:16 UTC, ykws commented on .gitignore
> +xcshareddata
なるほど、、 656684d0a2c2420c33d14dca77fe4339fe633680 に含まれていない `xcscheme` がありましたか

2022-06-07 07:30 UTC, daikiumehara commented on Yumemi-ios-training/ValueObject/Weather.swift
> +            return .sunny
noneというcaseを準備していたのはアプリをセッションごとに大きくしていく段階で、例外的なものを取得してしまう場面が出てくる可能性があるためでした。
セッションを進めていくにつれWeatherをCodable対応させるなど、例外的なものを取得することがないとわかったので、不必要な仕様と感じたので削除しました。

確かにこのコードではエラーを握りつぶす形になってしまっているので、適切なエラーハンドリングを行うように変更します！

2022-06-07 07:51 UTC, daikiumehara commented on Yumemi-ios-training/DIContainer/DIContainer.swift
> +    static func getWeatherPresenter(view: WeatherViewProtocol, weatherClient: WeatherClientProtocol) -> WeatherPresenterProtocol {
了解致しました。
では今回は勉強のために自分の思うやり方ではない書き方で行こうかなと思うのでここではこのまま進めていこうかなと思います！

2022-06-08 11:44 UTC, ykws approved these changes
エラーハンドリング確認しました。
あとは細かいところなので、次節以降で気に留めてもらえればと思います。

![LGTM](https://image.lgtmoon.dev/133009)

2022-06-08 11:44 UTC, ykws commented on Yumemi-ios-trainingTests/Mock/StubWeatherClient.swift
> +//  MockWeatherClient.swift
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

コメントの rename が漏れてました。

```suggestion
//  StubWeatherClient.swift
```

2022-06-08 11:44 UTC, ykws commented on Yumemi-ios-trainingTests/Mock/StubWeatherClient.swift
> +//
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

Group が Mock のままなので、 Stub に rename が漏れていました。

2022-06-08 11:44 UTC, ykws commented on Yumemi-ios-trainingTests/Mock/StubWeatherClient.swift
> +    func fetchWeather(area: String) throws -> Weather {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

上と同じように throws 省略可能でした。

2022-06-08 11:44 UTC, ykws commented on Yumemi-ios-trainingTests/Mock/StubWeatherClient.swift
> +    func fetchWeather(jsonString: String) throws -> InfraWeatherInfo {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

こちらも throws 省略可能でした。

2022-06-08 11:45 UTC, ykws commented on Yumemi-ios-training/ValueObject/Weather.swift
> +            return .sunny
✅ bd26bff9f77df64bdb44f58b889376fc0419083f

2022-06-08 14:29 UTC, merged