セッション9
daikiumehara/Yumemi-ios-training pull request #8
Opened 2022-05-12 12:03 UTC by daikiumehara

課題のURL：https://github.com/yumemi-inc/ios-training/blob/main/Documentation/ThreadBlock.md

# 変更点
非同期でデータを取得するように変更しました。
データを取得するまでIndicatorを表示するように変更しました。

# 実行時の様子
https://user-images.githubusercontent.com/62703773/168070381-0b907575-3cb2-47c0-90df-d01f0f801897.mov

2022-05-12 14:17 UTC, ykws requested changes
rebase がおそらく必要になると思いますが、テストコードの変更にも取り組んでみてください。

先に以下の対応を行うと良いと思います。

https://github.com/daikiumehara/Yumemi-ios-training/pull/7#discussion_r871431008

2022-05-13 09:37 UTC, daikiumehara commented
テストコードの変更というのは、非同期的な処理でデータを取得してテストを行うように変更するということでしょうか？

2022-05-13 12:56 UTC, daikiumehara commented
rebaseしてforce pushしました

2022-05-20 08:03 UTC, daikiumehara commented on Yumemi-ios-training/Mapper/Converter/WeatherImageConverter.swift
> +        case.sunny:
修正しました！

2022-05-25 12:27 UTC, ykws reviewed
Session8 の方を先に整理できてから見たいと思います。

https://github.com/daikiumehara/Yumemi-ios-training/pull/7#discussion_r881589915

2022-06-09 01:13 UTC, ykws commented on Yumemi-ios-trainingTests/Stub/StubWeatherClient.swift
> +        Thread.sleep(forTimeInterval: 1.0)
Stub で sleep したい動機は何でしょうか？
Stub の良いところは、 API がスレッドブロックしていてもいなくても等価的に扱えるところにあります。

2022-06-09 02:52 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Stub/StubWeatherClient.swift
> +        Thread.sleep(forTimeInterval: 1.0)
非同期のメソッドなのでデータ取得に時間がかかるのが理想的かなと思い、sleepを記述したんですが必要なかったでしょうか？

2022-06-10 01:31 UTC, ykws commented on Yumemi-ios-trainingTests/Stub/StubWeatherClient.swift
> +        Thread.sleep(forTimeInterval: 1.0)
sleep がない場合とあった場合でテストコードはどう変わるでしょうか。
それぞれにおいて何をテストできているか分析してみて、どういったテストの観点から必要であるか PR の概要やテストコードの差分にコメントをつけてみてください。

2022-06-10 02:55 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
sleepを追加することで、Mock用のPresenterを作成しXCTestExpectationを用いてデータの取得が完了するまで待機する必要があります。
そうすることで、データの取得が非同期であってもUIに正しく反映されることを保証することができます。
非同期でデータを取得した際に起こるエラー、不具合がないことを保証することができると考えています。

2022-06-10 07:40 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
> データの取得が非同期であってもUIに正しく反映されることを保証することができます。
非同期でデータを取得した際に起こるエラー、不具合がないことを保証することができると考えています。

これは本当にそうでしょうか？
データの取得処理は本体の実装と異なるのが Stub なので、 Stubの実装に対するテストになっていると考えます。

2022-06-10 08:20 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
本体の実装のテストは同期・非同期関係なくデータが渡された時に正しく表示されるかをテストするものであって、非同期のデータ取得が正しく行えているかのテストはStubの実装(Client)のテストになっているということでしょうか？

2022-06-10 09:49 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
> 本体の実装のテストは同期・非同期関係なくデータが渡された時に正しく表示されるかをテストするものであって

認識にズレがあるかもなので、言葉を足してみます。

まず本体の実装のままテストするのが困難なので Stub を利用しています。

Stub の導入には protocol を経由してデータのやり取りを定義する必要がありました。
protocol を経由するということは、実装に依存しないということになります。

Stub の導入によって、任意のデータを返せるようになりました。
Stub の返す任意のデータが**実装に関係なく**、正しく表示されるかテストするものになります。

> 非同期のデータ取得が正しく行えているかのテストはStubの実装(Client)のテストになっているということでしょうか？

というよりは、前述の**実装に関係なく**、という前提から外れて、現状の Stub の実装に依存したテストをしたい欲求に読み取れました。なので、 Stub の中身がどうであっても、 Stub の実装をテストしようとしているかどうかが焦点になると思います。

2022-06-10 11:30 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
なるほどです。
実装に依存しないというのはわかったのですが、
`func syncFetchWeather(_ jsonString: String) throws -> InfraWeatherInfo`
このメソッドは非同期でデータを取得することを前提としているメソッドだと思うのですが、
それであってもStubを非同期にする必要はないのでしょうか？

また、Stubを非同期にしなかった場合、非同期で正しく動いてることを確認するためにはどのようにテストを記述すれば良いのでしょうか？

2022-06-13 02:46 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
> このメソッドは非同期でデータを取得することを前提としているメソッドだと思うのですが、

ちょっと訂正です。 sync なので非同期ではなく、同期メソッドです。
同期メソッドを利用するために、アプリ側で非同期に処理する必要があるのが正しいです。

確かに、、 protocol の名前が良くないですね。。
段階的な研修ための命名で実装を区別しているため仕方ないですが。

> それであってもStubを非同期にする必要はないのでしょうか？

研修のための命名の都合なので、 Stub でもスレッドブロックする必要はないと考えます。

> また、Stubを非同期にしなかった場合、非同期で正しく動いてることを確認するためにはどのようにテストを記述すれば良いのでしょうか？

やるとしたら Unit Tests ではなく UI Tests の方が適切かと思います。
研修のオプション課題として挑戦してみますか？

🔖 [【Swift】初めてのUITest導入](https://qiita.com/taji-taji/items/c00e5b94376c37f17443)

2022-06-13 03:10 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
そうなんですね。
であれば、スレッドブロックなしで行こうと思います。

>やるとしたら Unit Tests ではなく UI Tests の方が適切かと思います。
>研修のオプション課題として挑戦してみますか？

そうですね。
あまり触れる機会がないのでやってみようと思います。
このPRでやってしまうとあまり良くないかなと思うのですが、どの部分で導入するべきでしょうか？

2022-06-14 00:01 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
session/9 から派生させて挑戦してもらえればと思います！

2022-06-14 00:02 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
スレッドブロックを削除してもらったので、 Presenter の Mock も不要になっているはずです！

bd286a8c2e95d19bd8b1abbd3224ce47949ddb78

2022-06-14 17:05 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
なぜかわからないのですが、またXCTestExpectationを用いないとErrorが発生するようになってしまったのですが、原因わかりますでしょうか？

2022-06-15 14:51 UTC, ykws reviewed
Reload 中に Reload ボタンをタップできてしまうので、連続でタップすると、
複数回天気予報の取得が実行されて、画面への表示が連続で切り替わってしまいます。

2022-06-15 14:51 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
以下について記載があるとフォローしやすいと思います。

- 具体的なエラーの内容
- どの状態でエラーが発生するか（コミットハッシュなど）

> XCTestExpectationを用いないとErrorが発生する

とあるので、 WeatherRepository が DispatchQueue によりスレッドを切り替えているのが関係してそうな気がします。

2022-06-15 17:24 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
エラー内容は以下です。
```
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```
コミットハッシュは`0c89faa58b9af03dfc1a8becf287af7ba7ad5111`です。

スレッドを切り替えているのが原因だと思うのですが、
スレッドを切り替えている場合であっても、XCTestExpectationを用いずに正しくテストするにはどうすれば良いのでしょうか？

2022-06-15 17:44 UTC, daikiumehara commented
reloadボタンが連続で押せないように修正しました。

2022-06-16 01:46 UTC, novr requested changes
Testが失敗します

`XCTAssertEqual(vc.weatherImageView.image!,~` でFatal error: Unexpectedly found nil while unwrapping an Optional value

2022-06-16 01:46 UTC, novr commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            DispatchQueue.main.async {
[IMO] DispatchQueue.main.asyncはUseCaseの責務ではないです

viewの更新はmain threadで実行を制約しているのは誰でしょうか？

2022-06-16 01:46 UTC, novr commented on Yumemi-ios-trainingTests/Mock/MockWeatherPresenter.swift
> +final class MockWeatherPresenter: WeatherPresenterProtocol {
[ASK] 使われない？

2022-06-16 04:12 UTC, daikiumehara commented
現在、テストでエラーが出る状況のものをpushしたので、のちにテストが通るように修正します。
https://github.com/daikiumehara/Yumemi-ios-training/pull/8#discussion_r898238111

2022-06-16 04:13 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Mock/MockWeatherPresenter.swift
> +final class MockWeatherPresenter: WeatherPresenterProtocol {
この部分の対応が完了次第、必要なさそうであれば削除します。
https://github.com/daikiumehara/Yumemi-ios-training/pull/8#discussion_r898059246

2022-06-16 04:37 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            DispatchQueue.main.async {
>viewの更新はmain threadで実行を制約しているのは誰でしょうか？

viewでしょうか？Viewでmainスレッドで更新させるというのが責務的には正しいように感じるのですが、
それぞれのメソッドにDispatchQueue.main.asyncを記述するのはとても助長になってしまうので、g
lobalのスレッドで実行される部分を最小限に抑えるという考え方のもとこの部分に記述しています。

2022-06-16 13:57 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
スレッドを切り替えている場合は、 XCTestExpectation を利用する必要があります。
スレッドに依存する部分を Stub で置き換えると利用しなくて済むようになります。

2022-06-16 17:25 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
ということはStubのRepositoryを作成するということでしょうか？
XCTestExpectationを用いるか、StubのRepositoryを作成するか、どちらが良いでしょうか？
Stubのrepositoryを作成する方がコードがシンプルになりそうでいいなと思います。

2022-06-17 02:22 UTC, novr commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            DispatchQueue.main.async {
まず前提として
`weatherRepository.syncFetchWeather`がどのように(globalのスレッドで)実行されるかをWeatherUseCaseは知りません、でないと暗黙の依存になってしまいます

Viewをmainスレッドで更新させるという責務はやはりViewですね
ただ、とても助長になると言うのはわかります
この場合は、callbackQueueを指定できるようにしてみるとよさそうです

2022-06-17 05:48 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            DispatchQueue.main.async {
>weatherRepository.syncFetchWeatherがどのように(globalのスレッドで)実行されるかをWeatherUseCaseは知りません、でないと暗黙の依存になってしまいます
そうなってしまっていますね。

>callbackQueueを利用側(View)から指定できるようにしてみるとよさそうです
正しく理解できているかわかりませんが、自分が理解したように記述してみたので、確認お願いします。

2022-06-17 08:14 UTC, novr commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            DispatchQueue.main.async {
概ね問題ないです
presenterで制御してもいいですし、useCaseでも大丈夫です
ようは自分以外の実装の詳細を知らないようにする(疎結合)事が大事です
ただ、presenterがprotocolとしてqueueを公開する必要はなさそうです
(presenterへ対して後から入れ替える要件はなさそう)
なのでWeatherPresenterのinitで渡すと不要なプロパティの公開をせず、さらに実装を隠蔽できます

2022-06-17 08:17 UTC, novr commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            DispatchQueue.main.async {
追記
Presenterで制御するならば、Viewを操作するのはPresenterの責務で
Viewを操作する際にmain threadを使うのは制約なので
そのままDispatchQueue.main.asyncを使っても良いと思います

2022-06-17 08:30 UTC, daikiumehara commented on Yumemi-ios-training/UseCase/WeatherUseCase.swift
> +            DispatchQueue.main.async {
そうなんですね。
であればuseCaseにcallbackQueueを持たせる方がコードがシンプルになりそうなので、useCaseに持たせるように変更してみます！

2022-06-21 00:40 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
複数の階層に分かれているので、丁寧にやるなら、以下のようにテストできるのが理想です。

- ViewControllerTest - StubPresenter
- PresenterTest - StubUseCase
- UseCaseTest - StubRepository
- RepositoryTest - StubClient

この課題としては、ここまで細かい階層は想定していなくて、
ViewController - StubModel の関係において、
中間の層は無視して、 Model に相当する Client の Stub を用意する方法で案内していました。

テストしやすいのが StubRepository を用意すること、というのは良い気づきだと思います。
そうした場合、 Client はテスト対象から除外されるので protocol として規定する必要性も無くなります。
テストが不要ならそもそも Client は Repository に含まれる内容とも言えます。

同じような観点から Presenter, UseCase, Repository を見直すと Client と同様のことが言えるかもしれません。

要件の規模に合わせて、テスト対象とそのために必要な階層をコントールできると良いと考えています。
アーキテクチャにアプリを合わせようとするのではなく、アプリに対してアーキテクチャを選択または規定できると良いと思っています。

2022-06-21 09:33 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
そうなんですね。確かにこの規模のアプリケーションには階層が厚いかもしれないです。
RepositoryとClientの責務について考えてみたのですが、
本来Clientでのデータの取得が同期であるか非同期であるかはわからないものなので、Repositoryでスレッドを切り替えているということがおかしいのではないかと感じました。
なので、スレッドの切り替えをClientで行うのf

2022-06-22 05:49 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
> UseCaseでスレッドの切り替え(メインスレッドへの切り替え)をおこなっているため、テストが失敗してしまいます。

そうですね。。メインスレッドへの切り替えも Client で行えば解消はできそうですが、、それが良いかですね。

> また、テストしやすい階層の厚いアプリケーションを作成する場合はどのような構造が適切なんでしょうか？

構造というより、基本的には隣り合う層同士のテストを書いていくのが良いと思います。

https://github.com/daikiumehara/Yumemi-ios-training/pull/8#discussion_r902068431

今回 ViewController のテストを書くわけですが、そうすると隣の Presenter があれば良くて、他の層はテストしないので protocol を用意しなくても良い感じに落ち着くと思います。
そうした状態で、層が分かれている利点があるのか見直してもらうと良いかもしれません。

XCTestException を使用しない形に注力せずに、必要な箇所で適切に利用するのは良いと思っています。

2022-06-22 05:51 UTC, ykws commented on Yumemi-ios-training/Client/WeatherClient.swift
> +                completion(.success(infraWeatherInfo))
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

Client でスレッド制御する場合

```suggestion
                DispatchQueue.main.sync {
                    completion(.success(infraWeatherInfo))
                }
```

2022-06-22 06:28 UTC, daikiumehara commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var presenter: MockWeatherPresenter!
Clientでのスレッド切り替えは望ましくないと思っています。
テスト用のClientとPresenterをを作成するは良くないと思うので、今回はPresenterを用いてテストを書こうと思います。
今回のアプリの規模だとUseCaseがデータをそのまま流すだけになっているので、不必要だったかなと感じています。
アプリの規模に応じて構造を考える良い機会になりました！🙇‍♂️

2022-06-23 02:10 UTC, novr commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            completion(.failure(.missDecode))
```suggestion
            completion(.failure(.missEncode))
```

2022-06-23 04:37 UTC, daikiumehara commented on Yumemi-ios-training/Repository/WeatherRepository.swift
> +            completion(.failure(.missDecode))
修正しました！

2022-06-24 01:59 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/81009)

2022-06-30 13:37 UTC, ykws approved these changes
以下の観点をクリアできているので良いと思いました！

- スレッドブロックの処理を利用する
- ロード中にイデジケータを表示する
- ロード中の Reload 処理を抑制する
- スレッドブロックに依存しないテストに変更する

![LGTM](https://image.lgtmoon.dev/133182)

ただ、 Client から Presenter のテストダブルに変わってしまったので、
変更前では Client＝API 側とモバイルアプリ側の問題の切り分けができる状態でしたが、
（テストが成功している限り、モバイルアプリ側は壊れていないことを担保できる状態）
変更後は、モバイルアプリ内の Presenter, UseCase, Repository はテスト対象に含まれていないため、問題の切り分けが困難な状態に変わっています。
（テストが成功していても、モバイルアプリ側が壊れていないことを担保できない状態）

これを改善するには、 Presenter, UseCase, Repository のテストを書いていくか、
過剰な層になっている傾向が見えるので、層を薄くしていく方針が考えられます。

2022-06-30 17:25 UTC, daikiumehara commented
ありがとうございます！
了解しました！
セッション13で修正してみます！

2022-06-30 17:25 UTC, merged